defmodule About.Repo.Migrations.InitialChatSetup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:chat_rooms, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :max_participants, :bigint
      add :is_public, :boolean
      add :description, :text
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:chat_participants, primary_key: false) do
      add :user_id,
          references(:users, column: :id, name: "chat_participants_user_id_fkey", type: :uuid)

      add :room_id,
          references(:chat_rooms,
            column: :id,
            name: "chat_participants_room_id_fkey",
            type: :uuid
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_seen_at, :utc_datetime_usec
      add :is_online, :boolean
      add :color, :text
      add :nickname, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:chat_messages, primary_key: false) do
      add :participant_id,
          references(:chat_participants,
            column: :id,
            name: "chat_messages_participant_id_fkey",
            type: :uuid
          ),
          null: false

      add :room_id,
          references(:chat_rooms, column: :id, name: "chat_messages_room_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :is_deleted, :boolean
      add :edited_at, :utc_datetime_usec
      add :type, :text
      add :content, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop constraint(:chat_messages, "chat_messages_room_id_fkey")

    drop constraint(:chat_messages, "chat_messages_participant_id_fkey")

    drop table(:chat_messages)

    drop constraint(:chat_participants, "chat_participants_room_id_fkey")

    drop constraint(:chat_participants, "chat_participants_user_id_fkey")

    drop table(:chat_participants)

    drop table(:chat_rooms)
  end
end
