defmodule About.Repo.Migrations.RemoveOnlineStatusFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:chat_participants) do
      # Remove online status fields as they are now handled by Phoenix Presence
      remove :last_seen_at
      remove :is_online

      add :joined_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:chat_participants) do
      remove :joined_at
      
      # Restore online status fields if rollback is needed
      add :is_online, :boolean
      add :last_seen_at, :utc_datetime_usec
    end
  end
end